# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chargify_api_ares"
  s.version = "0.3.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Klett", "The Lab Rats @ Phase Two Labs", "Brian Rose", "Nathan Verni"]
  s.date = "2011-10-13"
  s.description = ""
  s.email = "mklett@grasshopper.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "chargify_api_ares.gemspec",
    "config/remote.example.yml",
    "lib/chargify_api_ares.rb",
    "samples/customers.rb",
    "samples/metered_components.rb",
    "samples/products.rb",
    "samples/subscriptions.rb",
    "samples/transactions.rb",
    "spec/base_spec.rb",
    "spec/components_spec.rb",
    "spec/customer_spec.rb",
    "spec/factories.rb",
    "spec/mocks/fake_resource.rb",
    "spec/product_family_spec.rb",
    "spec/product_spec.rb",
    "spec/remote/remote_spec.rb",
    "spec/remote/spec_helper.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/subscription_spec.rb",
    "spec/subscriptions_component_spec.rb"
  ]
  s.homepage = "http://github.com/grasshopperlabs/chargify_api_ares"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Chargify API wrapper for Ruby using ActiveResource"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

